取引先一覧:
    columns:
        取引先CD: client_cd
        取引先名1: client_name1
        取引先名_全角: client_name_zenkaku
        取引先郵便番号: client_postal_code
        取引先住所: client_address
        電話番号: phone_number
        FAX番号: fax_number
        メールアドレス: email_address
        請求取引区分: billing_type
        営業担当者CD: sales_rep_cd
        集計項目CD: aggregate_item_cd
        集計項目名: aggregate_item_name

業者一覧:
    columns:
        業者CD: vendor_cd
        業者略称名: vendor_abbr_name
        営業担当者名: sales_rep_name
        業者担当者: vendor_contact_person
        業者郵便番号: vendor_postal_code
        業者都道府県名: vendor_prefecture
        業者住所1: vendor_address1
        電話番号: phone_number
        FAX番号: fax_number
        備考1: note1
        備考2: note2
        取引先CD: client_cd
        取引先名1: client_name1

品名一覧:
    columns:
        削除: deleted
        品名CD: item_cd
        品名: item_name
        略称: item_abbr
        フリガナ: item_kana
        単位: unit
        伝種区分: denshu_type
        伝票区分: slip_type
        税区分: tax_type
        種類CD: category_cd
        種類名: category_name
        分類CD: class_cd
        分類名: class_name
        適格返還: qualified_return
        廃棄物名称CD: waste_name_cd
        廃棄物名: waste_name
        処分方法CD: disposal_method_cd
        処分方法名: disposal_method_name
        産廃: industrial_waste
        混合: mixed
        マニ対象: manifest_target
        廃棄物種類CD（産廃用）: waste_type_cd_industrial
        廃棄物種類名（産廃用）: waste_type_name_industrial
        混合種類CD（産廃用）: mixed_type_cd_industrial
        混合種類名（産廃用）: mixed_type_name_industrial
        建廃: construction_waste
        混合.1: mixed_1
        廃棄物種類CD（建廃用）: waste_type_cd_construction
        廃棄物種類名（建廃用）: waste_type_name_construction
        混合種類CD（建廃用）: mixed_type_cd_construction
        混合種類名（建廃用）: mixed_type_name_construction
        積替: transfer
        混合.2: mixed_2
        廃棄物種類CD（積替用）: waste_type_cd_transfer
        廃棄物種類名（積替用）: waste_type_name_transfer
        混合種類CD（積替用）: mixed_type_cd_transfer
        混合種類名（積替用）: mixed_type_name_transfer
        電子: electronic
        廃棄物種類CD（電子用）: waste_type_cd_electronic
        廃棄物種類名（電子用）: waste_type_name_electronic
        実績分類CD: performance_class_cd
        実績分類名: performance_class_name
        更新者: updated_by
        更新日: updated_at
        作成者: created_by
        作成日: created_at
