# category_question_templates.yaml
# フロントエンドでカテゴリ/テンプレートに紐づく推奨タグを表示するための設定ファイル。
# 本番環境ではバックエンド config/category_question_templates.yaml と同期させる運用を想定。
# 形式例:
# 資材:
#   - title: "品質レポート"
#     tag: ["品質", "検査", "不良"]
#   - title: "安全確認"
#     tag: ["安全", "点検"]
# 物流:
#   - title: "出荷確認"
#     tag: ["出荷", "在庫"]
#
# ここでは暫定のダミーデータを記載。

デフォルト:
  - title: "自由入力"
    tag: []
