services:
  # =============================
  # フロントエンド（Reactアプリ）
  # 本番ではビルド済み静的ファイルを nginx から配信する運用が望ましい。
  # =============================
  frontend:
    build: ./my-project/frontend
    networks: [backend]
    restart: unless-stopped

  # =============================
  # AI API
  # =============================
  ai_api:
    build: ./my-project/backend/ai_api
    # サービス固有の値だけを env_file に残す（存在するファイルに限定）
    env_file: [./envs/.env.ai_api]
    # ルート .env の値を使って実行時へ明示注入（組み立てが必要な値はここで）
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      PYTHONPATH: ${PYTHONPATH:-/backend}
    depends_on:
      db:
        condition: service_healthy
    networks: [backend]
    restart: unless-stopped
    healthcheck:
      # Python標準ライブラリで /health を確認（curl/wget 不要）
      test:
        [
          "CMD-SHELL",
          "python - <<'PY'\nimport sys,urllib.request\ntry:\n  r=urllib.request.urlopen('http://localhost:8000/health', timeout=3)\n  sys.exit(0 if r.getcode()==200 else 1)\nexcept Exception:\n  sys.exit(1)\nPY",
        ]
      interval: 20s
      timeout: 5s
      retries: 5

  # =============================
  # Ledger API
  # =============================
  ledger_api:
    build: ./my-project/backend/ledger_api
    env_file: [./envs/.env.ledger_api]
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      PYTHONPATH: ${PYTHONPATH:-/backend}
    depends_on:
      db:
        condition: service_healthy
    networks: [backend]
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python - <<'PY'\nimport sys,urllib.request\ntry:\n  r=urllib.request.urlopen('http://localhost:8000/health', timeout=3)\n  sys.exit(0 if r.getcode()==200 else 1)\nexcept Exception:\n  sys.exit(1)\nPY",
        ]
      interval: 20s
      timeout: 5s
      retries: 5

  # =============================
  # SQL API
  # =============================
  sql_api:
    build: ./my-project/backend/sql_api
    # ここがポイント：存在しない ./envs/.env を外し、実在する専用ファイルだけに
    env_file: [./envs/.env.sql_api]
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      PYTHONPATH: ${PYTHONPATH:-/backend}
    depends_on:
      db:
        condition: service_healthy
    networks: [backend]
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python - <<'PY'\nimport sys,urllib.request\ntry:\n  r=urllib.request.urlopen('http://localhost:8000/health', timeout=3)\n  sys.exit(0 if r.getcode()==200 else 1)\nexcept Exception:\n  sys.exit(1)\nPY",
        ]
      interval: 20s
      timeout: 5s
      retries: 5

  # =============================
  # RAG API
  # =============================
  rag_api:
    build:
      context: ./my-project/backend/rag_api
      dockerfile: Dockerfile
    env_file: [./envs/.env.rag_api]
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
      PYTHONPATH: ${PYTHONPATH:-/backend}
    depends_on:
      db:
        condition: service_healthy
    networks: [backend]
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "python - <<'PY'\nimport sys,urllib.request\ntry:\n  r=urllib.request.urlopen('http://localhost:8000/health', timeout=3)\n  sys.exit(0 if r.getcode()==200 else 1)\nexcept Exception:\n  sys.exit(1)\nPY",
        ]
      interval: 20s
      timeout: 5s
      retries: 5

  # =============================
  # PostgreSQL DB
  # =============================
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Tokyo
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks: [backend]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 6

  # =============================
  # Nginx（外部公開用）
  # =============================
  nginx:
    image: nginx:1.27-alpine
    ports: ["80:80", "443:443"]
    volumes:
      - ./my-project/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./my-project/nginx/certs:/etc/nginx/certs:ro
    depends_on:
      ai_api:
        condition: service_healthy
      ledger_api:
        condition: service_healthy
      sql_api:
        condition: service_healthy
      rag_api:
        condition: service_healthy
    networks: [backend]
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  dbdata:
