version: '3.8'

services:
    frontend:
        build: ./my-project/my-dashboard-app
        container_name: react_app
        ports:
            - '5173:5173'
        volumes:
            - ./my-project/my-dashboard-app:/app
            - /app/node_modules # ✅ ここに追加
        working_dir: /app
        command: ['npm', 'run', 'dev', '--', '--host', '0.0.0.0']
        environment:
            - CHOKIDAR_USEPOLLING=true

    backend:
        build: ./my-project/backend
        container_name: fastapi_app
        ports:
            - '8000:8000'
        volumes:
            - ./my-project/backend:/app
        working_dir: /app
        env_file:
            - ./my-project/backend/.env
