services:
    web:
        build: .
        ports:
            - '5173:5173'
        volumes:
            - ./my-project:/app
        working_dir: /app
        tty: true
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
