# ✅ 共通カラム定義
columns:
    shipment: &shipment_cols
        - 業者CD
        - 業者名
        - 現場名
        - 金額
        - 正味重量
        - 伝票日付
        - 品名

    yard: &yard_cols
        - 種類名
        - 正味重量
        - 伝票日付
        - 品名

    receive: &receive_cols
        - 金額
        - 受入番号
        - 集計項目CD
        - 数量
        - 正味重量
        - 単位名
        - 単価
        - 伝票区分名
        - 伝票日付
        - 品名
        - 品名CD

# ✅ 各用途で参照
average_sheet:
    receive:
        - *receive_cols

factory_report:
    shipment: *shipment_cols
    yard: *yard_cols

balance_sheet:
    shipment: *shipment_cols
    yard:
        - *yard_cols
        - 数量
    receive: *receive_cols

block_unit_price:
    shipment:
        - 業者CD
        - 業者名
        - 正味重量
        - 数量
        - 単価
        - 明細備考
        - 伝票日付
        - 品名
        - 単位名

management_sheet:
    shipment: *shipment_cols
    yard:
        - *yard_cols
        - 数量
    receive:
        - *receive_cols

balance_management_table:
    shipment:
        - 伝票日付
        - 業者CD
        - 業者名
        - 取引先CD
        - 品名CD
        - 単位CD
        - 車種CD
        - 運搬業者CD
        - 種類CD
        - 正味重量
        - 金額

inbound_volume:
    receive:
        - 伝票日付
        - 正味重量
        - 品名
