version: "3.9"
services:
  frontend:
    build: { context: ../app/frontend, dockerfile: Dockerfile }
    env_file: [../env/.env.dev]
    networks: [app-net]
  ai_api:
    build: { context: ../app, dockerfile: backend/ai_api/Dockerfile }
    env_file: [../env/.env.dev]
    networks: [app-net]
  ledger_api:
    build: { context: ../app, dockerfile: backend/ledger_api/Dockerfile }
    env_file: [../env/.env.dev]
    networks: [app-net]
  sql_api:
    build: { context: ../app, dockerfile: backend/sql_api/Dockerfile }
    env_file: [../env/.env.dev]
    networks: [app-net]
  rag_api:
    build: { context: ../app, dockerfile: backend/rag_api/Dockerfile }
    env_file: [../env/.env.dev]
    networks: [app-net]
  nginx:
    build: { context: ../app, dockerfile: nginx/Dockerfile }
    depends_on: [frontend, ai_api, ledger_api, sql_api, rag_api]
    networks: [app-net]
    volumes:
      - ../app/nginx/conf.d:/etc/nginx/conf.d
      - ../app/nginx/certs:/etc/nginx/certs
networks:
  app-net: { driver: bridge }

