FROM python:3.10

WORKDIR /backend


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /backend/app

ENV PYTHONPATH=/backend

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
