from app.utils.utils import build_manual_asset_url


sections = [
    {
        "id": "master",
        "title": "マスター情報・登録",
        "icon": "FolderOpenOutlined",
        "items": [
            {
                "id": "customer",
                "title": "取引先",
                "route": "/manual/master/customer",
                "description": "取引先マスタの登録・更新・検索方法。新規取引先の追加、既存取引先情報の変更、取引先コードでの検索など、取引先管理の基本操作を解説します。",
                "thumbnail_url": "https://via.placeholder.com/400x300/4A90E2/ffffff?text=取引先マスタ",
                "tags": ["取引先", "マスター", "登録"],
            },
            {
                "id": "vendor",
                "title": "業者",
                "route": "/manual/master/vendor",
                "description": "運搬業者・処分業者マスタの管理方法。業者情報の登録、更新、業者区分の設定、許可証管理など、業者マスタに関する操作手順を詳しく説明します。",
                "flow_url": build_manual_asset_url("master/vender/vender_fllowchart.png"),
                "video_url": build_manual_asset_url("master/vender/vender_movie.mp4"),
                "thumbnail_url": build_manual_asset_url("master/vender/vender_fllowchart.png"),
                "tags": ["業者", "マスター", "運搬", "処分"],
            },
            {
                "id": "site",
                "title": "現場",
                "route": "/manual/master/site",
                "description": "現場マスタの登録・管理方法。建設現場の新規登録、現場情報の更新、現場コードの採番ルール、現場と取引先の紐付けなどを解説します。",
                "thumbnail_url": "https://via.placeholder.com/400x300/50C878/ffffff?text=現場マスタ",
                "tags": ["現場", "マスター", "建設"],
            },
            {
                "id": "unitprice",
                "title": "単価",
                "route": "/manual/master/unit-price",
                "description": "単価マスタの設定・管理方法。品目別単価の登録、取引先別単価の設定、期間別単価の管理、単価改定の手順などを詳しく説明します。",
                "thumbnail_url": "https://via.placeholder.com/400x300/F39C12/ffffff?text=単価マスタ",
                "tags": ["単価", "マスター", "価格"],
            },
            {
                "id": "item",
                "title": "品名",
                "route": "/manual/master/item",
                "description": "品名マスタの登録・分類管理方法。廃棄物・有価物の品名登録、品目コードの設定、品目分類の管理、マニフェスト品名との対応付けなどを解説します。",
                "thumbnail_url": "https://via.placeholder.com/400x300/9B59B6/ffffff?text=品名マスタ",
                "tags": ["品名", "マスター", "品目"],
            },
        ],
    },
    {
        "id": "contract",
        "title": "契約書",
        "icon": "FileProtectOutlined",
        "items": [
            {
                "id": "contract-reg-biz",
                "title": "登録関係（事業系）",
                "description": "事業系廃棄物の契約書登録フロー。契約書の新規作成、契約内容の入力、品目・単価の設定、契約期間の管理、契約書PDFの生成・保存方法を段階的に説明します。",
                "flow_url": "https://example.com/contract_biz_flow.pdf",
                "video_url": "https://example.com/contract_biz.mp4",
                "thumbnail_url": "https://via.placeholder.com/400x300/E74C3C/ffffff?text=事業系契約書",
                "route": "/manual/contract/biz",
                "tags": ["契約書", "事業系", "登録"],
            },
            {
                "id": "contract-reg-construction",
                "title": "登録関係（建設系）",
                "description": "建設系廃棄物の契約書登録フロー。現場との紐付け、建設系特有の品目設定、工期との連動、契約書の作成から保存までの一連の流れを詳しく解説します。",
                "flow_url": "https://example.com/contract_construction_flow.pdf",
                "video_url": "https://example.com/contract_construction.mp4",
                "thumbnail_url": "https://via.placeholder.com/400x300/E67E22/ffffff?text=建設系契約書",
                "route": "/manual/contract/construction",
                "tags": ["契約書", "建設系", "登録"],
            },
            {
                "id": "contract-search",
                "title": "検索",
                "route": "/manual/contract/search",
                "description": "契約書の検索・閲覧方法。取引先名、契約番号、契約期間などの条件指定による検索、契約書PDFの表示、契約内容の確認方法を説明します。",
                "thumbnail_url": "https://via.placeholder.com/400x300/3498DB/ffffff?text=契約書検索",
                "tags": ["契約書", "検索"],
            },
        ],
    },
    {
        "id": "estimate",
        "title": "見積書",
        "icon": "FileTextOutlined",
        "items": [
            {
                "id": "estimate-make",
                "title": "見積書の作成フロー",
                "flow_url": "https://example.com/estimate_flow.pdf",
                "video_url": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                "description": "見積書作成の全体フロー。取引先選択、品目・数量の入力、単価の自動設定、値引き・調整の方法、見積書PDFの作成・印刷、見積履歴の管理まで、見積作成に関する全ての操作を解説します。",
                "thumbnail_url": "https://via.placeholder.com/400x300/1ABC9C/ffffff?text=見積書作成",
                "route": "/manual/estimate",
                "tags": ["見積書", "作成", "PDF"],
            },
        ],
    },
    {
        "id": "manifest",
        "title": "マニフェスト",
        "icon": "FileDoneOutlined",
        "items": [
            {
                "id": "mf-honest-out",
                "title": "工場外のオネスト運搬のマニフェスト入力",
                "description": "工場外で発生したオネスト運搬案件のマニフェスト入力手順。排出場所の指定、運搬業者の選択、品目・数量の入力、マニフェスト番号の採番、各票の印刷方法を詳しく説明します。",
                "flow_url": "https://example.com/mf_honest_out_flow.pdf",
                "video_url": "https://example.com/mf_honest_out.mp4",
                "thumbnail_url": "https://via.placeholder.com/400x300/2ECC71/ffffff?text=オネスト運搬",
                "route": "/manual/manifest/honest-out",
                "tags": ["マニフェスト", "オネスト", "工場外", "運搬"],
            },
            {
                "id": "mf-search",
                "title": "マニフェストの検索",
                "route": "/manual/manifest/search",
                "description": "マニフェストの検索・照会方法。マニフェスト番号、交付日、排出事業者、運搬業者などの条件での検索、検索結果の絞り込み、マニフェスト詳細の確認方法を解説します。",
                "thumbnail_url": "https://via.placeholder.com/400x300/3498DB/ffffff?text=マニフェスト検索",
                "tags": ["マニフェスト", "検索", "照会"],
            },
            {
                "id": "mf-edit",
                "title": "マニフェストの修正",
                "route": "/manual/manifest/edit",
                "description": "既存マニフェストの修正方法。入力ミスの訂正、数量・品目の変更、修正履歴の記録、修正後の再印刷など、マニフェスト修正時の注意点と手順を説明します。",
                "thumbnail_url": "https://via.placeholder.com/400x300/F39C12/ffffff?text=マニフェスト修正",
                "tags": ["マニフェスト", "修正", "訂正"],
            },
            {
                "id": "mf-e-return",
                "title": "E票の返却",
                "description": "E票（処分終了票）の返却登録方法。処分業者からのE票受領確認、返却日の入力、返却内容のチェック、JWNETとの連携など、E票管理の一連の流れを詳しく解説します。",
                "flow_url": "https://example.com/mf_e_return.pdf",
                "video_url": "https://example.com/mf_e_return.mp4",
                "thumbnail_url": "https://via.placeholder.com/400x300/E74C3C/ffffff?text=E票返却",
                "tags": ["マニフェスト", "E票", "返却", "JWNET"],
            },
            {
                "id": "mf-e-check",
                "title": "E票・返却の有無確認",
                "route": "/manual/manifest/e-check",
                "description": "E票返却状況の確認方法。未返却マニフェストの一覧表示、返却期限のチェック、督促が必要な案件の抽出、返却状況レポートの出力方法を説明します。",
                "thumbnail_url": "https://via.placeholder.com/400x300/9B59B6/ffffff?text=E票確認",
                "tags": ["マニフェスト", "E票", "確認", "管理"],
            },
            {
                "id": "mf-ledger",
                "title": "台帳",
                "route": "/manual/manifest/ledger",
                "description": "マニフェスト台帳の閲覧・管理方法。法定保存期間に基づく台帳の整理、期間別の集計、台帳の印刷・PDF出力、行政報告用データの作成方法を解説します。",
                "thumbnail_url": "https://via.placeholder.com/400x300/34495E/ffffff?text=マニフェスト台帳",
                "tags": ["マニフェスト", "台帳", "保存", "報告"],
            },
        ],
    },
    {
        "id": "external-input",
        "title": "工場外入力",
        "icon": "CloudUploadOutlined",
        "items": [
            {
                "id": "ext-sales",
                "title": "売上のみ入力",
                "description": "工場外で発生した売上の直接入力方法。売上伝票の手動作成、取引先・品目・金額の入力、請求書との紐付け、売上データの確定手順を詳しく説明します。",
                "flow_url": "https://example.com/ext_sales_flow.png",
                "video_url": "https://example.com/ext_sales.mp4",
                "thumbnail_url": "https://via.placeholder.com/400x300/27AE60/ffffff?text=売上入力",
                "tags": ["工場外", "売上", "入力", "伝票"],
            },
            {
                "id": "ext-purchase",
                "title": "仕入のみの入力",
                "description": "工場外で発生した仕入の直接入力方法。仕入伝票の手動作成、仕入先・品目・金額の入力、支払予定との連携、仕入データの確定手順を詳しく説明します。",
                "flow_url": "https://example.com/ext_purchase_flow.png",
                "video_url": "https://example.com/ext_purchase.mp4",
                "thumbnail_url": "https://via.placeholder.com/400x300/E67E22/ffffff?text=仕入入力",
                "tags": ["工場外", "仕入", "入力", "伝票"],
            },
        ],
    },
]
