name: Build & Push Frontend (stg)

on:
  workflow_dispatch: {}

env:
  PROJECT_ID: sanbou-app
  REGION: asia-northeast1
  REPO: sanbou-repo
  IMAGE_TAG: stg

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Docker auth for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - uses: docker/setup-buildx-action@v3

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: my-project/frontend
          file: my-project/frontend/Dockerfile
          push: true
          tags: |
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/sanbou-frontend:${{ env.IMAGE_TAG }}
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/sanbou-frontend:${{ env.IMAGE_TAG }}-${{ github.sha }}
