name: Build & Push Frontend (stg)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: sanbou-app                         # ← 固定値でOK
          service_account_key: ${{ secrets.GCP_SA_KEY }} # 必須（JSON）
          export_default_credentials: true

      - name: Docker auth for Artifact Registry
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet

      - uses: docker/setup-buildx-action@v3

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: my-project/frontend
          file: my-project/frontend/Dockerfile
          push: true
          tags: |
            asia-northeast1-docker.pkg.dev/sanbou-app/sanbou-repo/sanbou-frontend:stg
            asia-northeast1-docker.pkg.dev/sanbou-app/sanbou-repo/sanbou-frontend:stg-${{ github.sha }}
