name: Build & Push images (main only)

on:
  push:
    branches: [ main ]   # ← main に push（=PRマージ）された時だけ実行
  # もし「Gitタグ v*.*.* を打った時だけ」にしたいなら上を消して↓を使う
  # push:
  #   tags: [ "v*.*.*" ]

env:
  REGION: asia-northeast1
  REPO: sanbou

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Auth Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Decide image tag
        id: meta
        run: |
          # main限定: 短SHAをタグに使う（例: 9f8a7c2）
          echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          # Gitタグ運用に切り替える場合は ref_name を使う:
          # echo "tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      # ここで5サービスをマトリクス一括ビルド
      - name: Build & Push (all services)
        uses: docker/build-push-action@v6
        with:
          # 複数サービスを個別に回したいので matrix を使うため、下の "strategy" に移動
          # （このステップはダミー、実処理は下のジョブで行う）
          context: .
        if: ${{ false }}  # 実行しない（説明用の占位）

  # ↑占位ステップの代わりに、サービスごとに並列ビルドするジョブ
  # （同一ワークフロー内で Job を分けるとキャッシュが効きづらいので、
  #   1ジョブ内で matrix strategy を使う方法に変更）
  matrix-build:
    runs-on: ubuntu-latest
    needs: build-push
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: frontend
            context: ./frontend
            dockerfile: ./frontend/Dockerfile
          - name: ai-api
            context: ./backend/ai_api
            dockerfile: ./backend/ai_api/Dockerfile
          - name: ledger-api
            context: ./backend/ledger_api
            dockerfile: ./backend/ledger_api/Dockerfile
          - name: sql-api
            context: ./sql_api
            dockerfile: ./sql_api/Dockerfile
          - name: rag-api
            context: ./rag_api
            dockerfile: ./rag_api/Dockerfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Auth Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute TAG again (needs-job scope)
        id: meta
        run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build & Push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPO }}/${{ matrix.name }}:${{ steps.meta.outputs.tag }}
          # 人間読みやすいタグ（例：v1.1.1）も付けたい場合は、タグ時トリガーに変えてここに追加:
          #   ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPO }}/${{ matrix.name }}:${{ github.ref_name }}
